name: Deploy App 

on:
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build Project
        run: ./gradlew build
      - name: Upload Artifacct for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: springboot-jar
          path: ${{ github.workspace }}/build/libs/*[!plain].jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Azure Web App
      uses: azure/cli@v1
      with:
        inlineScript: |
          az webapp deployment source config-zip --resource-group springboot-demo_group --name springboot-demo --src ${{ github.workspace }}/build/libs/spring_boot-0.0.1-SNAPSHOT.jar
          
    - name: Restart Azure Web App
      uses: azure/cli@v1
      with:
        inlineScript: |
          az webapp restart --name springboot --resource-group springboot-demo_group
