name: synk_scan

on:
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Snyk
        uses: snyk/actions/setup@v1
        with:
         version: 'latest'

         
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk17@master
        env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    